spin_version = "1"
authors = ["Rajat Jindal"]
description = ""
name = "test"
trigger = { type = "http", base = "/" }
version = "0.1.0"

# Redirect /spin/contributing/ to spin/contributing-spin
[[component]]
id = "preview-compare"
source = "main.wasm"
allowed_http_hosts = ["rajatjindal.com", "fermyon.com"]
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod", "spin.toml"]