spin_version = "1"
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = "preview url's side by side"
name = "preview-2"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "preview-2"
source = "main.wasm"
allowed_http_hosts = ["insecure:allow-all"]
key_value_stores = ["default"]
environment = { app_role = "preview-2" }
[component.trigger]
route = "/..."
[component.build]
command = ""
watch = ["main.wasm"]