spin_version = "1"
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = "preview url's side by side"
name = "preview-main"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "preview-compare"
source = "main.wasm"
allowed_http_hosts = ["insecure:allow-all"]
key_value_stores = ["default"]
environment = { app_role = "preview-main" }
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod", "spin.toml"]