spin_version = "1"
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = "preview url's side by side"
name = "preview-1"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "preview-1"
source = "main.wasm"
allowed_http_hosts = ["rajatjindal.com", "fermyon.com"]
environment = { app_role = "preview-1" }
[component.trigger]
route = "/..."
[component.build]
command = ""
watch = ["main.wasm"]